services:
  husarion_ugv_crsf_teleop:
    image: husarion/crsf-teleop:humble
    network_mode: host
    ipc: host
    pid: host
    restart: unless-stopped
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROBOT_MODEL_NAME=${ROBOT_MODEL_NAME:-panther}
    volumes:
      - /dev:/dev
    command: >
      ros2 launch husarion_ugv_crsf_teleop teleop.launch.py namespace:=panther
