services:
  husarion_ugv_crsf_teleop:
    image: husarion/crsf-teleop:humble
    network_mode: host
    ipc: host
    pid: host
    restart: unless-stopped
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-panther}
    volumes:
      - /dev:/dev
      - ./husarion_ugv_crsf_teleop/config:/config
    command: >
      ros2 launch husarion_ugv_crsf_teleop teleop.launch.py params_file:=/config/crsf_teleop_panther.yaml
