/**:
  crsf_teleop:
    ros__parameters:
      port: /dev/ttyUSBPAD
      baud: 576000
      cmd_vel_stamped: false
      e_stop_republish: false
      enable_cmd_vel_silence_switch: false
      linear_speed_presets: [0.4, 1.2, 2.0]
      angular_speed_presets: [0.39, 0.78, 1.88]
