/**:
  crsf_teleop:
    ros__parameters:
      port: /dev/ttyUSBPAD
      baud: 576000
      cmd_vel_stamped: false
      e_stop_republish: false
      enable_cmd_vel_silence_switch: false
      linear_speed_presets: [0.5, 0.9, 1.5]
      angular_speed_presets: [0.45, 0.9, 2.0]
