/**:
  crsf_teleop:
    ros__parameters:
      port: /dev/ttyUSBPAD
      baud: 576000
      cmd_vel_stamped: true
      cmd_vel_topic: cmd_vel
      e_stop_republish: false
      enable_cmd_vel_silence_switch: true
      linear_speed_presets: [0.4, 1.2, 2.0]
      angular_speed_presets: [0.39, 0.78, 1.88]
      send_telemetry: True
      use_sim_time: False
      channels_srv_setbool: []
      channels_srv_trigger: []
      channels_srv_empty: []
      channels_msg_float: []
      channels_msg_bool: []
